# Generated by Django 5.0.1 on 2024-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="lot_number",
            field=models.IntegerField(),
        ),
    ]
