# Generated by Django 5.0.1 on 2024-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_inventory_lot_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="lot_number",
            field=models.CharField(max_length=50),
        ),
    ]
